spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://prod-db:5432/book}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    hikari:
      connection-timeout: 5000
      maximum-pool-size: 20
  jpa:
    show-sql: false

schedule:
  active: false

logging:
  level:
    root: warn
